### ISSUE TITLE
Формация корабликов

### ISSUE THREAD

**Issue by kaduev13** [kaduev13/web-game#27]
1. В настоящий момент при вылете кораблей с планеты, они запускаются из одной точки. Необходимо распределить кораблики равномерно вокруг планеты при запуске.
2. При перемещении корабликов по сцене они не обращают внимания друг на друга. Необходимо доработать движок таким образом, чтобы кораблики огибали друг друга.

**Comment by mariner1** [comment]
Распределять вокруг планеты надо не совсем равномерно. Со стороны, в которую они полетят может быть больше кораблей
![game1](https://cloud.githubusercontent.com/assets/9083198/11864075/7e81e2e2-a4e5-11e5-9171-d7363f8bf76e.png)

**Comment by DenisDavidyuk** [comment]
Вся группа кораблей или просто кораблик должен обращать внимание на другие кораблики? Огибание влияет на скорость перемещения? Это задание нельзя выполнить на клиенте?

**Comment by mariner1** [comment]
Вся группа кораблей или просто кораблик должен обращать внимание на другие кораблики?Обращают внимание друг на друга в группе, т.е. держат формацию Огибание влияет на скорость перемещения?Возможно при огибании нужно притормозить в зависмости от угла поворота Это задание нельзя выполнить на клиенте?Нет, каждый корабль отдельно рассчитывается на сервере.
