### ISSUE TITLE
Динамический фон игровой сцены

### ISSUE THREAD

**Issue by kaduev13** [kaduev13/web-game#28]
Сделать бэкграунд сцены динамическим - космическое небо, по которому иногда пролетают кометы, на котором видны мигающие звезды / млечный путь, в общем сделать красиво. Использовать для всего этого дела WebGL.
Примеры того, что хотелось бы получить:

+ подложка из SR2 во время полета космосе
+ http://stars.chromeexperiments.com/
+ http://www.asterank.com/3d/

**Comment by DenisDavidyuk** [comment]
Можно использовать https://github.com/mattstyles/pixi-starfield ?
Эта штука случайным образом генерирует туманности и разбрасывает звёзды.
![default](https://cloud.githubusercontent.com/assets/9007851/12850305/c27c0fac-cc6f-11e5-88d7-8296eeb5ec50.PNG
